repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: end-of-file-fixer
        # PO files may not have a trailing EOL, as they are tool generated
        exclude: "locales"
      - id: trailing-whitespace
  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.1.0
    hooks:
      - id: rumdl
