[global]
flavor = "mkdocs"
include = ["**/*.md"]
exclude = ["comment.md", "docs-redirect/en/README.md", "CODE_OF_CONDUCT.md"]
respect-gitignore = true

# Disable rules:
# MD014: Forces commands in codeblocks to show output
# MD033: No inline HTML
disable = ["MD014", "MD033",]

[per-file-ignores]

[MD013]  # Line length
line_length = 999999
reflow = true
reflow_mode = "normalize"

[MD026]  # Remove punctuation at the end of headings
punctuation = ",;:"

[MD061]  # Fail on certain strings.
terms = ["TODO"]
