[dependency-groups]
pre-commit = [
    "pre-commit == 4.3.0",
]

redirects = [
    "mkdocs-redirects == 1.2.2",
]

tox-uv = [
    "tox-uv == 1.28.0",
]

dev = [
    {include-group = "pre-commit"},
    {include-group = "tox-uv"},
]

docs = [
    "beeware-docs-tools @ git+https://github.com/kattni/beeware-docs-tools@tooling/website-mkdocs-migration",
    {include-group = "redirects"},
]
