[dependency-groups]
pre-commit = [
    "pre-commit == 4.5.1",
]

redirects = [
    "mkdocs-redirects == 1.2.2",
]

tox-uv = [
    "tox-uv == 1.29.0",
]

dev = [
    {include-group = "pre-commit"},
    {include-group = "tox-uv"},
]

docs = [
    # TODO: Restore to beeware/beeware-docs-tools before going live.
    # "beeware-docs-tools @ git+https://github.com/beeware/beeware-docs-tools",
    "beeware-docs-tools @ git+https://github.com/kattni/beeware-docs-tools@tooling/website-mkdocs-migration",
    # "beeware-docs-tools @ file://../beeware-docs-tools",
    {include-group = "redirects"},
]

[tool.rumdl]
flavor = "mkdocs"
include = ["**/*.md"]
exclude = ["comment.md", "docs-redirect/en/README.md", "CODE_OF_CONDUCT.md"]
respect-gitignore = true

# Disable rules:
# MD014: Forces commands in codeblocks to show output
# MD033: No inline HTML
disable = ["MD014", "MD033",]

[tool.rumdl.per-file-ignores]
"docs/en/about/team/*.md" = ["MD041"]

[tool.rumdl.MD013]  # Line length
line_length = 999999
reflow = true
reflow_mode = "normalize"

[tool.rumdl.MD026]  # Remove punctuation at the end of headings
punctuation = ",;:"

[tool.rumdl.MD061]  # Fail on certain strings.
terms = ["TODO"]
